#pragma config(Motor,  motorA,          motorMedium,   tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  setMotorTarget(motorMedium, 1, 100);
  sleep(1000);
  setMotorTarget(motorMedium, -1, 100);
  sleep(1000);
}
