#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program assumes you are using the standard LEGO Education robot
Sensor Ports:
S1 = Touch
S2 = Gyro
S3 = Color
S4 = Sonar (Ultrasonic)

Motor Ports:
A = Arm Motor
B = Right Motor
C = Left Motor
*/

task main()
{
	float fDistance = 0;

	while (true)
	{
		// Distance returned in cm. Divide by 2.54 to convert to inches
		fDistance = getUSDistance(sonarSensor);

	  writeDebugStreamLine("Distance detected: %.1f cm", fDistance);
		sleep(100);
	}
	return;
}
