#pragma config(Sensor, S1,     Touch,          sensorEV3_Touch)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		// Turn the LED red if the touch sensor is pressed
		if (SensorValue[Touch])
		{
			displayCenteredBigTextLine(4, "Pressed!");
			setLEDColor(ledRed);
		}
		// If it's in a released state, turn the LED green
		else
		{
			displayCenteredBigTextLine(4, "Not Pressed!");
			setLEDColor(ledGreen);
		}
		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}
}
