#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program assumes you are using the standard LEGO Education robot
Sensor Ports:
S1 = Touch
S2 = Gyro
S3 = Color
S4 = Sonar (Ultrasonic)

Motor Ports:
A = Arm Motor
B = Right Motor
C = Left Motor
*/

task main()
{
	TLegoColors colour = colorNone;

	while (true)
	{
		colour = getColorName(colorSensor);

	  writeDebugStream("Colour detected: ");
		switch(colour)
		{
			case colorNone: writeDebugStreamLine("none"); break;
			case colorBlack: writeDebugStreamLine("black"); break;
			case colorBlue: writeDebugStreamLine("blue"); break;
			case colorGreen: writeDebugStreamLine("green"); break;
			case colorYellow: writeDebugStreamLine("yellow"); break;
			case colorRed: writeDebugStreamLine("red"); break;
			case colorWhite: writeDebugStreamLine("white"); break;
			case colorBrown: writeDebugStreamLine("brown"); break;
			default: writeDebugStreamLine("unknown");
		}
		sleep(100);
	}
	return;
}
