#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program assumes you are using the standard LEGO Education robot
Sensor Ports:
S1 = Touch
S2 = Gyro
S3 = Color
S4 = Sonar (Ultrasonic)

Motor Ports:
A = Arm Motor
B = Right Motor
C = Left Motor
*/

task main()
{
	long redValue;
	long greenValue;
	long blueValue;

	while (true)
	{
		getColorRGB(colorSensor, redValue, greenValue, blueValue);

	  writeDebugStreamLine("Colour detected: %d, %d, %d", redValue, greenValue, blueValue);
		sleep(100);
	}
	return;
}
