#pragma config(Sensor, S2,     IRRemote1,      sensorEV3_IRSensor, modeEV3IR_Remote)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
IR Seeker Modes
0 - modeEV3IR_Proximity
1 - modeEV3IR_Seeker
2 - modeEV3IR_Remote
3 - modeEV3IR_Remote_Advanced
5 - modeEV3IR_Calibration
*/

/*
IR Remote Mode Values:
0 - No button pressed
1 - Blue upper
2 - Blue lower
3 - Red upper
4 - Red lower
5 - Red upper and blue upper
6 - Red lower and blue upper
7 - Red upper and blue lower
8 - Red lower and blue lower
9 - Beacon (large button at top)
10 - Red upper and red lower
11 - Blue upper and blue lower
*/

// These are the values of the remote and the corresonding motor speeds
// Sensor Value       0   1    2    3    4   5    6    7    8   9  10 11
int rightSpeeds[] = { 0,  0,   0,  20, -20, 50, -20,  20, -50,  0,  0, 0};
int leftSpeeds[]  = { 0, 20, -20,   0,   0, 50,  20, -20, -50,  0,  0, 0};

task main()
{
	int remoteCommand = 0;
	//Turn the IR Seeker to "Remote" mode
	//setSensorMode(IRRemote1, modeEV3IR_Remote);

	while(true)
	{
		// Read the sensor
		remoteCommand = SensorValue[IRRemote1];
		if (remoteCommand < 12)
		{
			displayBigTextLine(4, "Right: %d", rightSpeeds[remoteCommand]);
			displayBigTextLine(6, "Left:  %d", leftSpeeds[remoteCommand]);
			// Set the motor speeds
			motor[motorRight] = rightSpeeds[remoteCommand];
			motor[motorLeft] = leftSpeeds[remoteCommand];
		}

		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}
}
