#pragma config(Sensor, S2,     IRBeacon,       sensorEV3_IRSensor, modeEV3IR_Seeker)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
IR Seeker Modes
0 - modeEV3IR_Proximity
1 - modeEV3IR_Seeker
2 - modeEV3IR_Remote
3 - modeEV3IR_Remote_Advanced
5 - modeEV3IR_Calibration
*/

task main()
{
	int currentPosition = 0;

	while(true)
	{
		// Read the sensor
	  // The position is a value from -25 (extreme left) to +25 (extreme right).
	  // 0 means either no beacon detected or a beacond dead-ahead.
		currentPosition = SensorValue[IRBeacon];

		displayCenteredBigTextLine(4, "Pos: %d", currentPosition);

		// If the sensor returns > 0, the beacon is to the right,
		// so turn the robot to the right to face it
		if (currentPosition > 0)
		{
			motor[motorLeft] = 30;
			motor[motorRight] = -30;
		}
		// If the sensor returns < 0, the beacon is to the left,
		// so turn the robot to the left to face it
		else if (currentPosition < 0)
		{
			motor[motorLeft] = -30;
			motor[motorRight] = 30;
		}
		// If the sensor returns 0, the sensor is either not
		// detecting anything or the beacon is straight in front
		else
		{
			motor[motorLeft] = 0;
			motor[motorRight] = 0;
		}

		//Loop to monitor value in Sensor debugger window
		sleep(50);
	}
}
