#pragma config(Sensor, S4,     irSensor,       sensorEV3_IRSensor)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program assumes you are using the standard LEGO Education robot
Sensor Ports:
S4 = IR (Infrared)

Motor Ports:
A = Arm Motor
B = Right Motor
C = Left Motor
*/

task main()
{
	TIRRemoteButtons buttons;

	while (true)
	{
		buttons = getIRRemoteButtons(irSensor);
		writeDebugStream("Buttons pressed: ");
		switch(buttons)
		{
			case IR_NONE: writeDebugStreamLine("none"); break;
			case IR_RED_UP: writeDebugStreamLine("red up"); break;
			case IR_RED_DOWN: writeDebugStreamLine("red down"); break;
			case IR_BLUE_UP: writeDebugStreamLine("blue up"); break;
			case IR_BLUE_DOWN: writeDebugStreamLine("blue down"); break;
			case IR_RED_UP_BLUE_UP: writeDebugStreamLine("red up, blue up"); break;
			case IR_RED_UP_BLUE_DOWN: writeDebugStreamLine("red up, blue down"); break;
			case IR_RED_DOWN_BLUE_UP: writeDebugStreamLine("red down, blue up"); break;
			case IR_RED_DOWN_BLUE_DOWN: writeDebugStreamLine("red down, blue down"); break;
			case IR_BEACON_MODE_ON: writeDebugStreamLine("beacon activated"); break;
			case IR_RED_UP_RED_DOWN: writeDebugStreamLine("red up, red down"); break;
			case IR_BLUE_UP_BLUE_DOWN: writeDebugStreamLine("blue up, blue down"); break;
			default: writeDebugStreamLine("illegal combo"); break;
		}
		sleep(100);
	}
	return;
}
