#pragma config(Sensor, S4,     irSensor,       sensorEV3_IRSensor, modeEV3IR_Seeker)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program assumes you are using the standard LEGO Education robot
Sensor Ports:
S4 = IR (Infrared)

Motor Ports:
A = Arm Motor
B = Right Motor
C = Left Motor
*/

task main()
{
	long nDirection = 0;
	long nStrength = 0;

	while (true)
	{
		// Strength returned in percent.
	  // Direction is a value from -25 for objects to the left
	  // +25 for objects to the right.
		nDirection = getIRBeaconDirection(irSensor);
		nStrength = getIRBeaconStrength(irSensor);

	  writeDebugStreamLine("Direction: %d, strength: %d", nDirection, nStrength);
	  displayBigTextLine(1, "Direction: %d", nDirection);
	  displayBigTextLine(3, "Strength: %d", nStrength);
		sleep(100);
	}
	return;
}
