#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeatUntil (getUSDistance(sonarSensor) <= 20) {
		lineTrackRight(colorSensor, 65, 75, 35);
	}
}
