#pragma config(Sensor, S2,     touchSensor,         sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                        - Multitasking  Demo -                                          *|
|*                                            ROBOTC on  NXT                                              *|
|*                                                                                                        *|
|*  This program is a very basic example of Multitasking using ROBOTC.  There are 3 Tasks: Main, TOne,    *|
|*  and TTwo.  Main starts tasks TOne and TTwo, running all 3 tasks simultaneously.  However, TTwo        *|
|*  doesn't do much until the Touch Sensor is activated.  Once activated, TOne will be terminated,        *|
|*  leaving Main and TTwo running simultaneously.  Once the Touch Sensor is deactivated, TTwo resumes     *|
|*  doing nothing, while Main and TOne run simultaneously again.  (This could be useful for running       *|
|*  certain display patterns in the background while 'real' code runs in the foreground, etc.)            *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  For this demo, no motors are required, just one Touch Sensor in Sensor Port 2.                  *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port 2                  touchSensor         Touch               NXT Touch Sensor                    *|
\*---------------------------------------------------------------------------------------------------4246-*/


// task TOne();    /* If Tasks are placed below Main in your code, list them all here like this above Main. */
// task TTwo();    /* Note** this is unnecessary for this code since the tasks are all above the Main Task. */


//==========================================================================================================================================

task TOne()
{
  while(true)
  {
    wait1Msec(300);                                 // Allow for a short wait, freeing up the CPU for other tasks.

    displayCenteredBigTextLine(3, "TASK 1");     // Display that TOne is running simultaneously with Main.

    displayClearTextLine(6);                     /* Erase TTwo's display since it isn't doing anything.              */
    displayClearTextLine(7);                     /* (Even though technically it is still running in the background.) */
  }
  return;
}

//==========================================================================================================================================
//==========================================================================================================================================

task TTwo()
{
  while(true)
  {
    wait1Msec(300);                                 // Allow for a short wait, freeing up the CPU for other tasks.

    while(SensorValue(touchSensor) == 1)            // While Touch Sensor is activated:
    {
      stopTask(TOne);                                     // Kill TOne.

      displayCenteredBigTextLine(6, "TASK 2");         // Display that TTwo is running simultaneously with Main.

	    displayClearTextLine(3);                         /* Erase TOne's display since it was killed.                          */
	    displayClearTextLine(4);                         /* (TOne is actually gone for now so only TTwo and Main are running.) */

	    wait1Msec(100);                                     // Wait a small amount to allow the NXT Display to display correctly.
    }
    startTask(TOne);                                // Start TOne again, running all 3 tasks simultaneously.
  }
  return;
}

//==========================================================================================================================================
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

task main()
{
  startTask(TOne);                             // Start Task TOne.
  startTask(TTwo);                             // Start Task TTwo.

  while(true)
  {
    wait1Msec(300);                                 // Allow for a short wait, freeing up the CPU for other tasks.

    displayCenteredBigTextLine(0, "TASK M");     // Display that Main is running.
  }
  return;
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
