
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

//TJoystick joystick;

task main()
{
  while (true)
  {
    getJoystickSettings(joystick);
    displayTextLine(0, "joy1_x1: %d", joystick.joy1_x1);
    displayTextLine(1, "joy1_y1: %d", joystick.joy1_y1);
    displayTextLine(2, "joy1_x2: %d", joystick.joy1_x2);
    displayTextLine(3, "joy1_y2: %d", joystick.joy1_y2);
    displayTextLine(4, "joy1_Buttons: %d", joystick.joy1_Buttons);
    displayTextLine(5, "joy1_TopHat: %d", joystick.joy1_TopHat);
    displayTextLine(6, "joy2_x1: %d", joystick.joy2_x1);
    displayTextLine(7, "joy2_y1: %d", joystick.joy2_y1);
    displayTextLine(8, "joy2_x2: %d", joystick.joy2_x2);
    displayTextLine(9, "joy2_y2: %d", joystick.joy2_y2);
    displayTextLine(10, "joy2_Buttons: %d", joystick.joy2_Buttons);
    displayTextLine(11, "joy2_TopHat: %d", joystick.joy2_TopHat);
    sleep(50);
  }
}
