#pragma config(Motor,  motorA,          MOT_A,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// center of the circle
#define CX						89
#define CY						19

// Radius of the circle
#define RADIUS 				69

task main()
{
	// This makes sure the motor can turn freely
	setMotorBrakeMode(MOT_A, motorCoast);
	motor[MOT_A] = 0;

	int x, y;

	float rpm;
	while (true)
	{
		eraseDisplay();
		rpm = getMotorRPM(MOT_A);

		x = CX + (RADIUS * sinDegrees(rpm - 90));
		y = CY + (RADIUS * cosDegrees(rpm - 90));

		// x -= CX - (x - CX);
		displayCenteredBigTextLine(1, "RPM of motorA");

		// EV3 screen is 178 x 128, so draw the circle in the middle
		drawCircle(20, 90, RADIUS * 2);
		drawCircle(CX - 2, CY + 2, 5);

		// Erase the bottom half
		eraseRect(0, 0, 178, 19);
		drawLine(20, 19, 156, 19);

		// Draw the actual RPM "arrow"
		drawLine(CX, CY, x, y);

		// Display the current RPM of the motor
		displayCenteredBigTextLine(14,"%3.1f", rpm);
    sleep(50);
	}
}
