#pragma config(Sensor, S2,     gyro,           sensorEV3_Gyro, modeEV3Gyro_Rate)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		// Set the gyro to read the rotational speed
		setSensorMode(gyro, modeEV3Gyro_Rate);
		for (int i = 0; i < 100; i++)
		{
			writeDebugStreamLine("Rate: %d", SensorValue[gyro]);
			sleep(10);
		}

		// When switching modes from Rate to Angle mode, the sensor is reset
		// This means that previous heading information is lost
		setSensorMode(gyro, modeEV3Gyro_Angle);
		for (int i = 0; i < 100; i++)
		{
			writeDebugStreamLine("Angle: %d", SensorValue[gyro]);
			sleep(10);
		}
	}
}
