#pragma config(Sensor, S4,     Gyro,           sensorEV3_Gyro, modeEV3Gyro_Angle)
#pragma config(Motor,  motorB,          motorLeft,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          motorRight,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Gyro modes
0 - modeEV3Gyro_Angle
1 - modeEV3Gyro_Rate
2 - modeEV3Gyro_Fast
3 - modeEV3Gyro_RateAndAngle
4 - modeEV3Gyro_Calibration - Not utilized
*/
task main()
{
	// The code below will rotate the robot 360 degrees and wait 1 second and repeat
	while (true)
	{
		// Set motor speeds to 20 and -20 to do a clockwise pivot turn
		motor[motorLeft] = 20;
		motor[motorRight] = -20;

		// Read the sensor's value.  The angle is cumulative, that means that
		// after 2 rotations, it will read 2 x 360 = 720 degrees.
		// When the sensor is turned counter-clockwise, the angle will go into
		// negative
		// We'll take the modulo 360 of it because we're not interested in
		// how many times we've turned.
		while ((SensorValue[Gyro] % 360) < 359)
			sleep(1);

		// Stop the robot and wait 1 second
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		sleep(1000);
	}
}
