#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
This program assumes you are using the standard LEGO Education robot
Sensor Ports:
S1 = Touch
S2 = Gyro
S3 = Color
S4 = Sonar (Ultrasonic)

Motor Ports:
A = Arm Motor
B = Right Motor
C = Left Motor
*/

task main()
{
	long nDegrees = 0;
	long nHeading = 0;
	long nRate = 0;

	while (true)
	{
		nDegrees = getGyroDegrees(gyroSensor);	// Value 0 to 360
		nHeading = getGyroHeading(gyroSensor);	// Value -180 to 180
		nRate = getGyroRate(gyroSensor);				// Value of -440 to 440;

		writeDebugStreamLine("nDegrees: %d, nHeading: %d, nRate: %d", nDegrees, nHeading, nRate);
		sleep(100);
	}

	return;
}
