#pragma config(Sensor, S1,     leftBumper,     sensorEV3_Touch)
#pragma config(Sensor, S2,     rightBumper,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task MovingForward();

//task ReflectionChanged();

/**Self Defined function*/
//void sideAction() {
//	displayTextLine(3, "Left: %i", getMotorSpeed(leftMotor));
//	displayTextLine(4, "Right: %i", getMotorSpeed(rightMotor));
//	stopTask(MovingForward);
//	if (getTouchValue(leftBumper) == 1) {
//		setMotorSpeed(leftMotor, -20);
//		setMotorSpeed(rightMotor, -20);
//		wait1Msec(1000);
//
//		resetMotorEncoder(leftMotor);
//		while(getMotorEncoder(leftMotor)<=360) {
//			setMotorSyncEncoder(leftMotor, rightMotor, -100, 360, -30);
//		}
//	} else if (getTouchValue(rightBumper) == 1) {
//		setMotorSyncEncoder(leftMotor, rightMotor, 0, 360, -30);
//		setMotorSyncEncoder(leftMotor, rightMotor, 100, 360, -30);
//	}
//	startTask(MovingForward);
//}

void getTarget() {

}

void turn(int degree) {
	 stopTask(MovingForward);
	 moveMotorTarget(leftMotor, 90, 30);
	 moveMotorTarget(rightMotor, -90, 30);
	 repeatUntil(getMotorEncoder(
	 //motor[leftMotor] = -30;
	 //motor[rightMotor] = -30;
}


task main()
{
 // int maxColor = getColorReflected(colorSensor);
 // int minColor = getColorReflected(colorSensor);
	//int previousColor = getColorReflected(colorSensor);
	int count = 0; // count the number of tile run over
	TLegoColors previousColor = getColorName(colorSensor);
	TLegoColors currentColor = getColorName(colorSensor);
	// Begin to move!
	//startTask(MovingForward);

	// moving until the colorSensor detect 10 tiles
	while(count<=10) {

		// === Use Sensor to get Color ===
		 displayBigTextLine(2, "Count: %d", count);
		 displayBigTextLine(4, "P: %s", previousColor);
		 displayBigTextLine(6, "C: %s", currentColor);

		 if (previousColor != currentColor) {
		 		previousColor = currentColor;
		 		if (currentColor == colorBlack) {
		 			count++;
		 			playSound(soundBeepBeep);
		 		}
		 }


		 if (SensorValue(leftBumper) == 1) {break;}

		// === End of Color function ===
	}

	// After moving 15 tiles, stop!
	stopTask(MovingForward);
} // END of main()


/**Moving Class*/
task MovingForward() {
	setMotorSync(leftMotor, rightMotor, 0, 30);
}



//task MovingBackward() {
//	stopTask(MovingForward);
//	setMotorSync(leftMotor, rightMotor, 0, -30);
//	setMotorSpeed(leftMotor, -30);
//	setMotorSpeed(rightMotor, -30);
//}




///**Sensor Color Class*/
//task ReflectionChanged() {
//  int maxColor = 0;
//  int minColor = 100;
//  int currentColor = 0;
//  int previousColor = 0;

//	currentColor = getColorReflected(colorSensor);
//	displayTextLine(2, "Reflection: %d", currentColor);

//	if (currentColor > maxColor) {
//		maxColor = currentColor;
//	}
//	if (currentColor < minColor) {
//		minColor = currentColor;
//	}


//}
