#pragma config(Sensor, S1,     leftBumper,     sensorEV3_Touch)
#pragma config(Sensor, S2,     rightBumper,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//task showInfo();
task getDistanceAndDegree();
task MovingForward();


float distance = getUSDistance(sonarSensor);
float previousDistance = getUSDistance(sonarSensor);

float scanDegree = 45;
float targetDegree = 0;
float targetDistance = 100000;

bool toScan = false;
bool updateTarget = false;

int recordedDegree=0;

void turn(int degreeToTurn){
     startTask(getDistanceAndDegree);

	 int turningSpeed = 7;
	 degreeToTurn = degreeToTurn * 2;
	 resetMotorEncoder(leftMotor);
	 resetMotorEncoder(rightMotor);
	
	 if (degreeToTurn > 0) {
	 		setMotorTarget(leftMotor, degreeToTurn, turningSpeed);
	 		setMotorTarget(rightMotor, -degreeToTurn, turningSpeed);
	 		while(getMotorEncoder(leftMotor)!=getMotorTarget(leftMotor)) {
	   		setMotorSync(leftMotor, rightMotor, 100, turningSpeed);
	 		}
	} else if (degreeToTurn < 0) {
			degreeToTurn = -1 * degreeToTurn;
			setMotorTarget(leftMotor, -degreeToTurn, turningSpeed);
	 		setMotorTarget(rightMotor, degreeToTurn, turningSpeed);
	 		while(getMotorEncoder(rightMotor)!=getMotorTarget(rightMotor)) {
	   		setMotorSync(leftMotor, rightMotor, -100, turningSpeed);
	 		}
	}
	
	stopTask(getDistanceAndDegree);
}

void scan() {
	// reset my status of scan, except targetDistance.
	recordedDegree = 0;
	targetDegree = 0;
	toScan = false;
	updateTarget = false;
	
	turn(scanDegree)
	toScan = true;
	// Begin to scan
	turn(-2*scanDegree);
	toScan = false;
	
	if (updateTarget) {
		turn(targetDegree);
	} else {
		turn(scanDegree);
	}
	
}


task main()
{
	
	while (int i = 0; i < 5; i++) {
		scan();
		startTask(MovingForward);
		sleep(2000);
		stopTask(MovingForward);
	}

}

task getDistanceAndDegree() {
		if (toScan) {
			while(true) {
				recordedDegree = getMotorEncoder(rightMotor)/2;
				distance = getUSDistance(sonarSensor);
				
				if (distance < previousDistance && distance < targetDistance) {
					previousDistance = distance;
					targetDegree = recordedDegree;
				}
			}
			
			if (previousDistance < targetDistance) {
				targetDistance = previousDistance;
				targetDegree = 2*scanDegree - targetDegree;
				updateTarget = true;
			} else {
				updateTarget = false;
			}
		}		
}

task MovingForward() {
	setMotorSync(leftMotor, rightMotor, 0, 30);
}

//task showInfo(){
//	while(true) {
//			displayBigTextLine(2, "Left: %d", getMotorEncoder(leftMotor));
//			displayBigTextLine(4, "Right: %d", getMotorEncoder(rightMotor));
//			displayBigTextLine(6, "distance: %.2f", distance);
//			displayBigTextLine(8, "");
//	}
//}
