#pragma config(Sensor, S1,     leftBumper,     sensorEV3_Touch)
#pragma config(Sensor, S2,     rightBumper,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task showInfo();
task getDistanceAndDegree();


float distance = getUSDistance(sonarSensor);
float previousDistance = getUSDistance(sonarSensor);

float targetDegree = 0;
float targetDistance = 0;

bool toScan = false;
bool getMinimum = false;

int recordedDegree=0;

void turn(int degreeToTurn){
	 if (toScan) {startTask(getDistanceAndDegree);}
	 int turningSpeed = 7;
	 degreeToTurn = degreeToTurn * 2;
	 resetMotorEncoder(leftMotor);
	 resetMotorEncoder(rightMotor);
	 if (degreeToTurn > 0) {
	 		setMotorTarget(leftMotor, degreeToTurn, turningSpeed);
	 		setMotorTarget(rightMotor, -degreeToTurn, turningSpeed);
	 		while(getMotorEncoder(leftMotor)!=getMotorTarget(leftMotor)) {
	   		setMotorSync(leftMotor, rightMotor, 100, turningSpeed);
	 		}
	} else if (degreeToTurn < 0) {
			degreeToTurn = -1 * degreeToTurn;
			setMotorTarget(leftMotor, -degreeToTurn, turningSpeed);
	 		setMotorTarget(rightMotor, degreeToTurn, turningSpeed);
	 		while(getMotorEncoder(rightMotor)!=getMotorTarget(rightMotor)) {
	   		setMotorSync(leftMotor, rightMotor, -100, turningSpeed);
	 		}
		if (toScan) {stopTask(getDistanceAndDegree);}
	}

}



task main()
{

	int scanDegree = 45;
	toScan=true;
  turn(scanDegree);

  toScan=false;
	turn(-scanDegree);

	toScan=true;
	turn(-scanDegree);
	toScan=false;
	turn(scanDegree);

	turn(targetDegree);

	//while(true){
	//		displayBigTextLine(6, "distance: %.2f", targetDistance);
	//		displayBigTextLine(8, "degree: %d", targetDegree);
	//}

}

task showInfo(){
	while(true) {
			displayBigTextLine(2, "Left: %d", getMotorEncoder(leftMotor));
			displayBigTextLine(4, "Right: %d", getMotorEncoder(rightMotor));
			displayBigTextLine(6, "distance: %.2f", distance);
			displayBigTextLine(8, "");
	}

}


task getDistanceAndDegree() {
		while(true) {
			recordedDegree = getMotorEncoder(leftMotor)/2;
			distance = getUSDistance(sonarSensor);
			if (distance < previousDistance) {
				previousDistance = distance;
				targetDegree = recordedDegree;
			}
		}
		targetDegree = previousDistance;
		targetDistance = previousDistance;
}
