#pragma config(Sensor, S1,     leftBumper,     sensorEV3_Touch)
#pragma config(Sensor, S2,     rightBumper,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task showInfo();
task getDistanceAndDegree();


float distance = getUSDistance(sonarSensor);
float previousDistance = getUSDistance(sonarSensor);

float scanDegree = 45;
float targetDegree = 0;
float targetDistance = 1000;

bool toScan = false;
bool getMinimum = false;

int recordedDegree=0;

void turn(int degreeToTurn){
     startTask(getDistanceAndDegree);

	 int turningSpeed = 7;
	 degreeToTurn = degreeToTurn * 2;
	 resetMotorEncoder(leftMotor);
	 resetMotorEncoder(rightMotor);
	 if (degreeToTurn > 0) {
	 		setMotorTarget(leftMotor, degreeToTurn, turningSpeed);
	 		setMotorTarget(rightMotor, -degreeToTurn, turningSpeed);
	 		while(getMotorEncoder(leftMotor)!=getMotorTarget(leftMotor)) {
	   		setMotorSync(leftMotor, rightMotor, 100, turningSpeed);
	 		}
	} else if (degreeToTurn < 0) {
			degreeToTurn = -1 * degreeToTurn;
			setMotorTarget(leftMotor, -degreeToTurn, turningSpeed);
	 		setMotorTarget(rightMotor, degreeToTurn, turningSpeed);
	 		while(getMotorEncoder(rightMotor)!=getMotorTarget(rightMotor)) {
	   		setMotorSync(leftMotor, rightMotor, -100, turningSpeed);
	 		}
	
	  stopTask(getDistanceAndDegree);
	}

}

void scan() {
	recordedDegree = 0;
	targetDegree = 0;
	toScan = false;
	turn(scanDegree)
	
	// Begin to scan
	toScan = true;
	turn(-2*scanDegree);
	toScan = false;
	turn(targetDegree)
}


task main()
{
	
	while (int i = 0; i < 5; i++) {
		scan();
		
	}

}

task showInfo(){
	while(true) {
			displayBigTextLine(2, "Left: %d", getMotorEncoder(leftMotor));
			displayBigTextLine(4, "Right: %d", getMotorEncoder(rightMotor));
			displayBigTextLine(6, "distance: %.2f", distance);
			displayBigTextLine(8, "");
	}

}


task getDistanceAndDegree() {
		if (toScan) {
			while(true) {
				recordedDegree = getMotorEncoder(rightMotor)/2;
				distance = getUSDistance(sonarSensor);
				
				if (distance < previousDistance) {
					previousDistance = distance;
					targetDegree = recordedDegree;
				}
			}
			targetDegree = 2*scanDegree - targetDegree;
			targetDistance = previousDistance;
		}		
}


