#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Move both motors 360 degrees from their current position - robot will move 1 rotation forward
	moveMotorTarget(leftMotor, 360, 50);
	moveMotorTarget(rightMotor, 360, 50);

	//Delay the program until both motors complete their movements.
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	//Move both motors 720 degrees from their current position - robot will move 2 rotation forward
	moveMotorTarget(leftMotor, 720, 50);
	moveMotorTarget(rightMotor, 720, 50);

	//Delay the program until both motors complete their movements.
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
}
