#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Set both motors to target "360 degrees" - robot will move 1 rotation forward (0 -> 360)
	setMotorTarget(leftMotor, 360, 50);
	setMotorTarget(rightMotor, 360, 50);

	//Delay the program until both motors complete their movements.
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);

	//Set both motors to target "720 degrees" - robot will move 1 rotation forward (360 -> 720)
	setMotorTarget(leftMotor, 720, 50);
	setMotorTarget(rightMotor, 720, 50);

	//Delay the program until both motors complete their movements.
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightMotor);
}
