#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setLEDColor(ledGreenFlash);
	repeatUntil (getUSDistance(sonarSensor) < 20) {
		setMotor(motorB, 50);
		setMotor(motorC, 50);
	}
	setLEDColor(ledRed);
	stopAllMotors();
	wait(5, seconds);
}
