#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setLEDColor(ledGreenFlash);
	forward(3, seconds, 50);
	wait(2, seconds);
	setLEDColor(ledOrange);
	backward(3, seconds, 50);
}
